In [1]:
#perspektifi degistirmek neden onemli: biz yamuk olan nesnelerin tespitini yapabilyoruz ama goruntu ıslemede oyle degıl
#duz olanı ogrenırse yamuk olanı bilemeyebilir. o yuzden nesneleri cevire cevire anlamlandırmasını saglıyoruz.

In [5]:
import cv2
import pandas as pd
import numpy as np

In [3]:
#resmi ice aktarıyoruz
img = cv2.imread("ronaldo.jpg")
cv2.imshow("Original Ronaldo", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
#resim boyutlarına bakalım
width = 550
height =450

pts1 = np.float32([[0,0],[0,height],[width,0],[width,height]])
pts2 = np.float32([[230,1],[1,472],[540,150],[338,617]])
#buraya ilk once yamuk olan & duz olup da yamultmak istedigimiz nesnemizin onceki ve olmasını istedigimiz sonraki kordinatlarını
#giriyoruz.

matrix = cv2.getPerspectiveTransform(pts1, pts2)
#1. perspektiften 2. perspektife cevirttiriyoruz.
print(matrix)

[[ 5.91318031e-01 -5.09029375e-01  2.30000000e+02]
 [ 2.78598443e-01  9.80357115e-01  1.00000000e+00]
 [ 5.12623462e-05 -1.40486339e-04  1.00000000e+00]]


In [17]:
#cevirme islemini gerceklestiriyoruz.
imgOutput = cv2.warpPerspective(img, matrix, (width,height))     #burada en sondaki resmimizin olmasını istedigimiz boyudur.
cv2.imshow("Donusturulmus Resim", imgOutput)
cv2.waitKey(0)
cv2.destroyAllWindows()